server:
  port: 7070

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    fetch-registry: false #不从注册中心拉取注册表

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/exam?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
